name: Build and Release

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create MCPacks
        run: |
          zip -r KeyframeLite_BP.mcpack BP/*
          zip -r KeyframeLite_RP.mcpack RP/*
          zip -r KeyframeLite_Addon.mcaddon BP RP pack_icon.png

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            KeyframeLite_BP.mcpack
            KeyframeLite_RP.mcpack
            KeyframeLite_Addon.mcaddon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send to Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD }}
          content: "🚀 New Build for KeyframeLite Animation Mod!"
          title: "KeyframeLite Addon Build"
          description: "A new version of KeyframeLite has been built and is ready for testing."
          color: 0x0984e3
          file: "KeyframeLite_Addon.mcaddon"
