name: Build and Release

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create MCPacks
        run: |
          zip -r KeyframeLite_BP.mcpack BP/*
          zip -r KeyframeLite_RP.mcpack RP/*
          zip -r KeyframeLite_Addon.mcaddon BP RP pack_icon.png

      - name: Send to Discord
        uses: sinProject-Inc/discord-webhook-action@v2.0.0
        with:
          webhook_url: ${{ secrets.DISCORD }}
          content: "**KEYFRAME LITE ++ BY BAHOST01 (#agente0981 In Discord)**\n🚀 New Build for KeyframeLite Animation Mod!"
          filename: KeyframeLite_Addon.mcaddon

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            KeyframeLite_BP.mcpack
            KeyframeLite_RP.mcpack
            KeyframeLite_Addon.mcaddon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
